version: '3.9'
services:
  my-node-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    depends_on:
      - mongodb
    env_file:
      - .env 

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017

